version: '3.9'

networks: 
  dev_network: 

services: 
  db: 
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment: 
      POSTGRES_DB: flask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres